// src/core/platform/socialExportEngine.js
import fs from "fs";
import path from "path";

const EXPORT_DIR = path.resolve("server-renders/social-exports");

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function clean(value = "") {
  return String(value || "").replace(/\s+/g, " ").trim();
}

function makeHashtags({ topic = "", platform = "TikTok" } = {}) {
  const tags = [
    "#AstraMind",
    "#AstraMindTechnologies",
    "#AIVideo",
    "#ContentCreation",
  ];

  const text = topic.toLowerCase();

  if (text.includes("ai")) tags.push("#ArtificialIntelligence");
  if (text.includes("trump")) tags.push("#Politics", "#Trump");
  if (text.includes("business")) tags.push("#Business");
  if (text.includes("finance")) tags.push("#Finance");
  if (platform.toLowerCase().includes("youtube")) tags.push("#Shorts");
  if (platform.toLowerCase().includes("tiktok")) tags.push("#TikTok");

  return [...new Set(tags)].slice(0, 12);
}

export async function generateSocialExportPackage({
  projectId,
  topic = "",
  platform = "TikTok",
  style = "cinematic",
  videoPath,
  storyboard = {},
  captions = [],
  productionPlan = {},
  metadata = {},
} = {}) {
  ensureDir(EXPORT_DIR);

  const packagePath = path.join(EXPORT_DIR, `${projectId}_social_export.json`);

  const hashtags =
    Array.isArray(storyboard.hashtags) && storyboard.hashtags.length
      ? storyboard.hashtags
      : makeHashtags({ topic, platform });

  const caption =
    storyboard.caption ||
    `${clean(topic)}\n\nGenerated by AstraMind Technologies.`;

  const payload = {
    ok: true,
    engine: "AstraMind Social Export Engine v1",
    projectId,
    topic,
    platform,
    style,
    videoPath,
    caption,
    hashtags,
    captions,
    productionPlan,
    metadata,
    packagePath,
    createdAt: new Date().toISOString(),
    exports: {
      tiktok: {
        recommendedCaption: caption,
        hashtags,
      },
      youtubeShorts: {
        title: clean(topic).slice(0, 90),
        description: caption,
        hashtags,
      },
      instagramReels: {
        caption,
        hashtags,
      },
      x: {
        post: `${clean(topic).slice(0, 220)}\n\n${hashtags
          .slice(0, 4)
          .join(" ")}`,
      },
    },
  };

  fs.writeFileSync(packagePath, JSON.stringify(payload, null, 2), "utf8");

  return payload;
}

export function getSocialExportHealth() {
  return {
    ok: true,
    engine: "AstraMind Social Export Engine v1",
    exportDir: EXPORT_DIR,
    supports: {
      tiktok: true,
      youtubeShorts: true,
      instagramReels: true,
      x: true,
      hashtagGeneration: true,
      captionPackaging: true,
    },
  };
}

export default {
  generateSocialExportPackage,
  getSocialExportHealth,
};