import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext.js";
import { useSubscription } from "../context/SubscriptionContext.js";
import "../styles/pricing-realm.css";

const API_URL = process.env.REACT_APP_API_URL || "http://localhost:5000";
export default function Pricing() {
  const navigate=useNavigate(); const { token,isAuthenticated }=useAuth(); const { subscription,refresh }=useSubscription();
  const [plans,setPlans]=useState([]); const [interval,setInterval]=useState("monthly"); const [loading,setLoading]=useState(""); const [error,setError]=useState(""); const [ledger,setLedger]=useState([]);
  useEffect(()=>{fetch(`${API_URL}/api/billing/catalog`).then(r=>r.json()).then(d=>setPlans(d.plans||[])).catch(()=>setError("Pricing catalog is unavailable."));},[]);
  useEffect(()=>{if(!token)return;fetch(`${API_URL}/api/billing/usage?limit=8`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json()).then(d=>setLedger(d.ledger||[])).catch(()=>{});},[token,subscription?.creditsBalance]);
  const checkout=async(planId)=>{if(!isAuthenticated)return navigate("/login",{state:{from:{pathname:"/pricing"}}});setLoading(planId);setError("");try{const response=await fetch(`${API_URL}/api/billing/create-checkout-session`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({planId,interval})});const data=await response.json();if(!response.ok)throw new Error(data.error);window.location.assign(data.url);}catch(e){setError(e.message||"Checkout failed.");setLoading("");}};
  const portal=async()=>{const response=await fetch(`${API_URL}/api/billing/portal`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`}});const data=await response.json();if(data.url)window.location.assign(data.url);else setError(data.error);};
  return <main className="pricing-realm"><div className="pricing-stars"/><section className="pricing-shell"><header><small>ASTRAMIND SUBSCRIPTION REALM</small><h1>Choose the power of<br/><em>your creator universe.</em></h1><p>One operating system. Three levels of intelligence, production capacity, and autonomy.</p><div className="billing-toggle"><button className={interval==="monthly"?"active":""} onClick={()=>setInterval("monthly")}>Monthly</button><button className={interval==="yearly"?"active":""} onClick={()=>setInterval("yearly")}>Yearly <span>2 months free</span></button></div></header>{error&&<div className="pricing-error">{error}</div>}<div className="pricing-grid">{plans.map(plan=><article className={`pricing-card ${plan.id==="pro"?"featured":""}`} key={plan.id}>{plan.id==="pro"&&<div className="popular">MOST POPULAR</div>}<div className="plan-orb">✦</div><h2>{plan.name}</h2><div className="plan-price"><strong>${interval==="yearly"?plan.yearlyPrice:plan.monthlyPrice}</strong><span>/{interval==="yearly"?"year":"month"}</span></div>{interval==="yearly"&&<p className="effective">${(plan.yearlyPrice/12).toFixed(2)}/month effective</p>}<ul><li>{plan.monthlyCredits.toLocaleString()} monthly credits</li><li>{plan.projectLimit.toLocaleString()} stored projects</li><li>{plan.entitlements.images?"Image Studio":"Script and research tools"}</li><li>{plan.entitlements.video?"Cinematic video rendering":"Video preflight previews"}</li><li>{plan.entitlements.automation?"Mission automation & connectors":plan.entitlements.brandKit?"Brand kit & premium voices":"Standard production queue"}</li></ul><button onClick={()=>checkout(plan.id)} disabled={loading===plan.id||subscription?.planId===plan.id}>{subscription?.planId===plan.id?"Current realm":loading===plan.id?"Opening portal...":`Choose ${plan.name}`}</button></article>)}</div>{subscription&&<section className="credit-observatory"><div><small>CREDIT OBSERVATORY</small><h2>{subscription.creditsBalance.toLocaleString()} credits remain</h2><p>{subscription.plan?.name} · resets with your monthly credit period</p></div><div className="credit-actions"><button onClick={()=>refresh()}>Refresh balance</button>{subscription.stripeCustomerId&&<button onClick={portal}>Manage billing</button>}</div>{ledger.length>0&&<div className="ledger-list">{ledger.map(item=><div key={item.id}><span>{item.operation}</span><b>{item.amount} credits</b><small>{item.status} · {new Date(item.createdAt).toLocaleDateString()}</small></div>)}</div>}</section>}</section></main>;
}
