import React, { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useOSMode } from "../../context/ModeContext.js";
import { useAuth } from "../../context/AuthContext.js";
import { OS_MODES } from "../../core/os/modes.js";
import { API_URL } from "../../config/api.js";
import { AUDIO_GENRES, AUDIO_INSTRUMENTS } from "../../core/audio/AudioCatalog.js";
import { analyzeRhymes } from "../../core/audio/RhymeAnalysisEngine.js";
import "../../styles/audio-studio.css";
import "../../styles/rhyme-map.css";

const initialForm = { prompt:"", title:"", genre:"Auto", mood:"Uplifting", bpm:120, durationSeconds:150, lyricsMode:"astramind", instrumentMode:"astramind", selectedInstruments:[], generateVideo:false, lyricsText:"" };

export default function ContentAudio() {
  const { setMode } = useOSMode();
  const { token } = useAuth();
  const navigate = useNavigate();
  const [form,setForm] = useState(initialForm);
  const [sessions,setSessions] = useState([]);
  const [session,setSession] = useState(null);
  const [loading,setLoading] = useState(false);
  const [renderingWaveform,setRenderingWaveform] = useState(false);
  const [renderingVocals,setRenderingVocals] = useState(false);
  const [vocalStyle,setVocalStyle] = useState("warm expressive male lead vocalist");
  const [providerHealth,setProviderHealth] = useState(null);
  const [notice,setNotice] = useState("");
  const [manifest,setManifest] = useState(null);
  const [lyricsDraft,setLyricsDraft] = useState("");
  const [showLyricGenerator,setShowLyricGenerator] = useState(false);
  const [generatingLyrics,setGeneratingLyrics] = useState(false);
  const [lyricBrief,setLyricBrief] = useState({ prompt:"", structure:"Verse 1, Pre-Chorus, Chorus, Verse 2, Bridge, Final Chorus", perspective:"first person", rhymeDensity:"balanced", contentRating:"clean", notes:"" });
  const headers = useMemo(()=>({"Content-Type":"application/json",Authorization:`Bearer ${token}`}),[token]);
  const rhymeAnalysis = useMemo(()=>analyzeRhymes(lyricsDraft),[lyricsDraft]);
  const musicProviderLabel = providerHealth?.musicProviderLabel || "Aigenikz Music Engine";
  const musicReady = Boolean(providerHealth?.musicGenerationConfigured);
  const setField = (field,value)=>setForm((current)=>({...current,[field]:value}));

  useEffect(()=>setMode(OS_MODES.CONTENT),[setMode]);
  const loadSessions = async()=>{ try { const response=await fetch(`${API_URL}/api/audio-studio/sessions`,{headers,credentials:"include"}); const data=await response.json(); if(!response.ok)throw new Error(data.error||"Audio Studio could not load sessions."); setSessions(data.sessions||[]); } catch(error) { setNotice(error.message||"Audio Studio backend is unavailable."); } };
  const loadProviderHealth = async()=>{ try { const response=await fetch(`${API_URL}/api/audio-studio/health`,{headers,credentials:"include"}); const data=await response.json(); if(response.ok)setProviderHealth(data); } catch { setProviderHealth(null); } };
  useEffect(()=>{loadSessions();},[]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{loadProviderHealth();},[]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>setLyricsDraft(session?.lyrics?.text||""),[session?.id,session?.lyrics?.text]);

  const toggleInstrument=(name)=>setForm((current)=>({...current,selectedInstruments:current.selectedInstruments.includes(name)?current.selectedInstruments.filter((item)=>item!==name):[...current.selectedInstruments,name]}));
  const prepareVideoHandoff=(audioSession)=>{
    const instruments=(audioSession.tracks||[]).filter((track)=>track.type!=="vocal").map((track)=>track.name);
    const lyrics=audioSession.lyrics?.text||"Instrumental composition";
    localStorage.setItem("astramind_handoff",JSON.stringify({
      path:"/content/video", route:"Video Studio", source:"audio-studio", createdAt:new Date().toISOString(), platform:"YouTube",
      style:`cinematic ${audioSession.genre} music video`,
      prompt:`Create a synchronized cinematic music video for "${audioSession.title}", a ${audioSession.genre} song with a ${audioSession.mood} mood at ${audioSession.bpm} BPM. Build scenes around this song concept: ${audioSession.prompt}\n\nInstrumentation: ${instruments.join(", ")}.\n\nLyrics/song structure:\n${lyrics.slice(0,12000)}\n\nMatch scene pacing, transitions, captions, and visual beats to the song arrangement.`,
      audioSession:{id:audioSession.id,title:audioSession.title,genre:audioSession.genre,mood:audioSession.mood,bpm:audioSession.bpm,durationSeconds:audioSession.durationSeconds,key:audioSession.key,instruments}
    }));
  };
  const createSession=async()=>{ setLoading(true);setNotice("");try{const response=await fetch(`${API_URL}/api/audio-studio/sessions`,{method:"POST",headers,credentials:"include",body:JSON.stringify({...form,instrumental:form.lyricsMode==="instrumental",lyricsText:form.lyricsMode==="manual"?form.lyricsText:""})});const data=await response.json();if(!response.ok)throw new Error(data.error);let createdSession=data.session;setLyricsDraft(createdSession?.lyrics?.text||"");setManifest(null);if(createdSession?.videoIntent?.requested)prepareVideoHandoff(createdSession);const renderResponse=await fetch(`${API_URL}/api/audio-studio/sessions/${createdSession.id}/render`,{method:"POST",headers,credentials:"include",body:"{}"});const renderData=await renderResponse.json();if(renderResponse.ok&&renderData.session)createdSession=renderData.session;setSession(createdSession);setNotice(renderResponse.ok?`Song created from one prompt. Your playable WAV preview is ready${createdSession?.videoIntent?.requested?" and the matching video brief was prepared":""}.`:data.warning||"Composition created. Use Render playable WAV to retry the audio preview.");await loadSessions();}catch(error){setNotice(error.message);}finally{setLoading(false);} };
  const updateMixer=async(track,changes)=>{setSession({...session,tracks:session.tracks.map((item)=>item.id===track.id?{...item,...changes}:item)});try{const response=await fetch(`${API_URL}/api/audio-studio/sessions/${session.id}/mixer`,{method:"PATCH",headers,credentials:"include",body:JSON.stringify({trackId:track.id,...changes})});const data=await response.json();if(response.ok)setSession(data.session);else throw new Error(data.error);}catch(error){setNotice(error.message);} };
  const exportSession=async(format)=>{const response=await fetch(`${API_URL}/api/audio-studio/sessions/${session.id}/export`,{method:"POST",headers,credentials:"include",body:JSON.stringify({format})});const data=await response.json();if(response.ok)setManifest(data.manifest);else setNotice(data.error);};
  const renderWaveform=async()=>{setRenderingWaveform(true);setNotice("");try{const response=await fetch(`${API_URL}/api/audio-studio/sessions/${session.id}/render`,{method:"POST",headers,credentials:"include",body:"{}"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Waveform rendering failed.");setSession(data.session);setNotice("Aigenikz rendered a playable native WAV preview. Sung vocals require a separate singing-voice provider.");await loadSessions();}catch(error){setNotice(error.message);}finally{setRenderingWaveform(false);}};
  const renderVocalSong=async()=>{if(!session?.lyrics?.text?.trim()){setNotice("Save lyrics before generating a sung version.");return;}if(!musicReady){setNotice("Connect the Aigenikz Music worker before generating a full vocal song.");return;}const providerNote=providerHealth?.selfHostedMusic?"This runs on your connected Aigenikz worker.":"This uses the configured external provider and may incur provider charges.";if(!window.confirm(`Generate the full vocal song with ${musicProviderLabel}? ${providerNote}`))return;setRenderingVocals(true);setNotice(`Generating the full song with ${musicProviderLabel}. This can take several minutes; keep this page open.`);try{const response=await fetch(`${API_URL}/api/audio-studio/sessions/${session.id}/render-vocals`,{method:"POST",headers,credentials:"include",body:JSON.stringify({vocalStyle})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Vocal song generation failed.");setSession(data.session);setNotice(`Full song rendered by ${musicProviderLabel}. Review the result, then download it if approved.`);await loadSessions();}catch(error){setNotice(error.message);}finally{setRenderingVocals(false);}};
  const saveLyrics=async()=>{const response=await fetch(`${API_URL}/api/audio-studio/sessions/${session.id}/lyrics`,{method:"PATCH",headers,credentials:"include",body:JSON.stringify({text:lyricsDraft})});const data=await response.json();if(response.ok){setSession(data.session);setNotice("Lyrics and rhyme map saved.");await loadSessions();}else setNotice(data.error);};
  const generateLyrics=async()=>{const prompt=lyricBrief.prompt.trim()||form.prompt.trim();if(!prompt){setNotice("Describe the song before generating lyrics.");return;}setGeneratingLyrics(true);setNotice("");try{const response=await fetch(`${API_URL}/api/audio-studio/lyrics/generate`,{method:"POST",headers,credentials:"include",body:JSON.stringify({...lyricBrief,prompt,title:form.title,genre:form.genre,mood:form.mood})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Lyrics could not be generated.");setLyricsDraft(data.lyrics);setField("lyricsText",data.lyrics);setField("lyricsMode","manual");setNotice(data.warning||"Original lyric draft generated and sent to the Color Rhyme Map.");setShowLyricGenerator(false);}catch(error){setNotice(error.message);}finally{setGeneratingLyrics(false);} };
  const openVideoStudio=()=>{if(session)prepareVideoHandoff(session);navigate("/content/video");};

  return <div className="audio-studio-page">
    <header className="audio-studio-hero"><div><p>Creator Studio · Composition + production</p><h1>🎙️ Audio & Music Studio</h1><span>Turn one prompt into original lyrics, an arrangement, playable native audio, and an optional synchronized video brief.</span></div><div className="audio-provider"><strong>Aigenikz Waveform online</strong><span>Native WAV preview</span><strong className={musicReady?"provider-ready":"provider-offline"}>{musicReady?`${musicProviderLabel} connected`:"Full-song engine not connected"}</strong></div></header>
    {notice&&<div className="audio-notice">{notice}</div>}
    <div className="audio-studio-layout">
      <aside className="audio-card audio-composer"><p className="audio-kicker">Single-prompt composer</p><h2>New song</h2>
        <label>Creative direction<textarea value={form.prompt} onChange={(event)=>setField("prompt",event.target.value)} placeholder="One prompt is enough: describe the story, genre, energy, audience, and intended use..."/></label>
        <button type="button" className="audio-jump-link" onClick={()=>document.getElementById("song-type-controls")?.scrollIntoView({behavior:"smooth",block:"start"})}>↓ Choose song type, instruments & video</button>
        {form.lyricsMode!=="instrumental"&&<button type="button" className="audio-lyric-link" onClick={()=>{setLyricBrief((current)=>({...current,prompt:current.prompt||form.prompt}));setShowLyricGenerator((value)=>!value);}}>✍️ {showLyricGenerator?"Close Lyric Architect":"Open advanced Lyric Architect"}</button>}
        {showLyricGenerator&&form.lyricsMode!=="instrumental"&&<section className="audio-lyric-generator"><p className="audio-kicker">Aigenikz Lyric Architect</p><h3>Generate an original draft</h3><label>Lyric prompt<textarea value={lyricBrief.prompt} onChange={(event)=>setLyricBrief({...lyricBrief,prompt:event.target.value})}/></label><label>Song structure<input value={lyricBrief.structure} onChange={(event)=>setLyricBrief({...lyricBrief,structure:event.target.value})}/></label><div className="audio-form-grid"><label>Perspective<select value={lyricBrief.perspective} onChange={(event)=>setLyricBrief({...lyricBrief,perspective:event.target.value})}><option>first person</option><option>second person</option><option>third person</option></select></label><label>Rhyme density<select value={lyricBrief.rhymeDensity} onChange={(event)=>setLyricBrief({...lyricBrief,rhymeDensity:event.target.value})}><option>light</option><option>balanced</option><option>dense</option></select></label><label>Content<select value={lyricBrief.contentRating} onChange={(event)=>setLyricBrief({...lyricBrief,contentRating:event.target.value})}><option>clean</option><option>radio clean</option><option>mature</option></select></label></div><label>Additional notes<textarea value={lyricBrief.notes} onChange={(event)=>setLyricBrief({...lyricBrief,notes:event.target.value})}/></label><button type="button" className="audio-primary" onClick={generateLyrics} disabled={generatingLyrics}>{generatingLyrics?"Writing original lyrics…":"Generate lyric draft"}</button><small>Creates original lyrics only; it will not imitate a living artist.</small></section>}
        <label>Title<input value={form.title} onChange={(event)=>setField("title",event.target.value)} placeholder="Optional working title"/></label>
        <section id="song-type-controls" className="audio-choice-panel"><h3>Song design</h3><div className="audio-form-grid"><label>Type of song<select value={form.genre} onChange={(event)=>setField("genre",event.target.value)}>{AUDIO_GENRES.map((value)=><option key={value}>{value}</option>)}</select></label><label>Mood<input value={form.mood} onChange={(event)=>setField("mood",event.target.value)}/></label><label>BPM<input type="number" min="50" max="200" value={form.bpm} onChange={(event)=>setField("bpm",Number(event.target.value))}/></label><label>Duration (seconds)<input type="number" min="30" max="600" value={form.durationSeconds} onChange={(event)=>setField("durationSeconds",Number(event.target.value))}/></label></div>
          <span className="audio-field-title">Lyrics</span><div className="audio-option-grid"><label><input type="radio" name="lyrics-mode" checked={form.lyricsMode==="astramind"} onChange={()=>setField("lyricsMode","astramind")}/> Aigenikz writes lyrics</label><label><input type="radio" name="lyrics-mode" checked={form.lyricsMode==="manual"} onChange={()=>setField("lyricsMode","manual")}/> I will provide lyrics</label><label><input type="radio" name="lyrics-mode" checked={form.lyricsMode==="instrumental"} onChange={()=>setField("lyricsMode","instrumental")}/> Instrumental only</label></div>
          {form.lyricsMode==="manual"&&<label>Your lyrics<textarea value={form.lyricsText} onChange={(event)=>setField("lyricsText",event.target.value)} placeholder="Paste or write your original lyrics..."/></label>}
          <span className="audio-field-title">Music & instruments</span><div className="audio-option-grid"><label><input type="radio" name="instrument-mode" checked={form.instrumentMode==="astramind"} onChange={()=>setField("instrumentMode","astramind")}/> Aigenikz builds the music</label><label><input type="radio" name="instrument-mode" checked={form.instrumentMode==="manual"} onChange={()=>setField("instrumentMode","manual")}/> I choose the instruments</label></div>
          {form.instrumentMode==="manual"&&<div className="audio-instrument-grid">{AUDIO_INSTRUMENTS.map((name)=><label key={name}><input type="checkbox" checked={form.selectedInstruments.includes(name)} onChange={()=>toggleInstrument(name)}/>{name}</label>)}</div>}
          <label className="audio-video-option"><input type="checkbox" checked={form.generateVideo} onChange={(event)=>setField("generateVideo",event.target.checked)}/><span><strong>Create a matching AI music video</strong><small>Send the song concept, lyrics, instruments, and timing to Video Studio.</small></span></label>
        </section>
        <button className="audio-primary" onClick={createSession} disabled={loading||!form.prompt.trim()||(form.instrumentMode==="manual"&&!form.selectedInstruments.length)}>{loading?"Composing song...":"Generate song from this prompt"}</button>
        <div className="audio-session-vault"><h3>Session vault</h3>{sessions.length===0?<span>No sessions yet.</span>:sessions.map((item)=><button key={item.id} onClick={()=>setSession(item)}><strong>{item.title}</strong><small>{item.genre} · {item.bpm} BPM · v{item.version}</small></button>)}</div>
      </aside>
      <main className="audio-card audio-workstation">{!session?<div className="audio-empty"><strong>Start a composition</strong><span>Your lyrics, arrangement, mixer, and video handoff will appear here.</span></div>:<>
        <div className="audio-session-header"><div><p className="audio-kicker">Pro Tools-style session</p><h2>{session.title}</h2><span>{session.genre} · {session.mood} · {session.bpm} BPM · {session.key} · {session.timeSignature}</span></div><div className="audio-export"><button onClick={renderWaveform} disabled={renderingWaveform}>{renderingWaveform?"Rendering…":"Render playable WAV"}</button><button onClick={()=>exportSession("stems")}>Stem manifest</button><button onClick={()=>exportSession("json")}>JSON</button></div></div>
        {session.lyrics?.text&&<section className="audio-vocal-render"><div><p className="audio-kicker">Full-song vocal renderer</p><h3>Give the composition a singing voice</h3><span>{musicProviderLabel} performs the saved lyrics with the arrangement. Select a vocal direction, not a real artist.</span></div><label>Vocal direction<select value={vocalStyle} onChange={(event)=>setVocalStyle(event.target.value)}><option>warm expressive male lead vocalist</option><option>warm expressive female lead vocalist</option><option>soulful male vocalist with clear country phrasing</option><option>soulful female vocalist with clear country phrasing</option><option>rhythmic country rap vocalist with a melodic chorus</option><option>male and female duet with close harmonies</option><option>gritty baritone storyteller with restrained delivery</option><option>bright alto vocalist with confident delivery</option></select></label><button type="button" onClick={renderVocalSong} disabled={renderingVocals||!musicReady}>{renderingVocals?"Generating full vocal song…":"Generate full vocal song"}</button><small>{providerHealth?.selfHostedMusic?"Runs through your Aigenikz generation worker without per-song provider credits.":"External provider usage may incur charges. Provider credentials stay on the server."}</small></section>}
        {session.waveform?.publicUrl&&<section className="audio-waveform-player"><div><strong>Aigenikz native waveform</strong><span>{session.waveform.durationSeconds}s · {session.waveform.sampleRate} Hz · procedural preview</span></div><audio controls preload="metadata" src={`${API_URL}${session.waveform.publicUrl}`}/><a href={`${API_URL}${session.waveform.publicUrl}`} download>Download WAV</a><small>Lyrics guide composition and video timing; this native preview does not synthesize sung words.</small></section>}
        {session.vocalRender?.publicUrl&&<section className="audio-waveform-player audio-vocal-player"><div><strong>Full vocal master</strong><span>{session.vocalRender.durationSeconds}s · {session.vocalRender.providerLabel||session.vocalRender.provider||musicProviderLabel} · {session.vocalRender.vocalStyle}</span></div><audio controls preload="metadata" src={`${API_URL}${session.vocalRender.publicUrl}`}/><a href={`${API_URL}${session.vocalRender.publicUrl}`} download>Download {String(session.vocalRender.format||"mp3").toUpperCase()}</a><small>AI-generated singing voice and music. Review lyrics, pronunciation, mix, and usage rights before publication.</small></section>}
        {session.videoIntent?.requested&&<section className="audio-video-handoff"><div><strong>Matching music video brief ready</strong><span>Open Video Studio with the song concept, lyrics, instrumentation, and timing loaded.</span></div><button onClick={openVideoStudio}>Open Video Studio →</button></section>}
        <section className="audio-arrangement"><h3>Arrangement</h3><div className="audio-timeline">{session.sections.map((section)=><div key={section.id} style={{flex:section.bars}} title={`${section.startSeconds}s–${section.endSeconds}s`}><strong>{section.name}</strong><small>{section.bars} bars · {section.energy}%</small></div>)}</div><p>Progression: {session.progression.join(" → ")}</p></section>
        <section className="audio-mixer"><h3>Mixer</h3>{session.tracks.map((track)=><article key={track.id} style={{borderLeftColor:track.color}}><div className="audio-track-name"><strong>{track.name}</strong><small>{track.type} · {track.clips.length} clips</small></div><label>Volume <input type="range" min="-60" max="12" value={track.volumeDb} onChange={(event)=>updateMixer(track,{volumeDb:Number(event.target.value)})}/><span>{track.volumeDb} dB</span></label><label>Pan <input type="range" min="-100" max="100" value={track.pan} onChange={(event)=>updateMixer(track,{pan:Number(event.target.value)})}/><span>{track.pan}</span></label><button className={track.mute?"active":""} onClick={()=>updateMixer(track,{mute:!track.mute})}>M</button><button className={track.solo?"active solo":""} onClick={()=>updateMixer(track,{solo:!track.solo})}>S</button><div className="audio-effects">{track.effects.map((effect)=><span key={effect.type}>{effect.type} {effect.amount}%</span>)}</div></article>)}</section>
        {session.lyrics&&<section className="audio-lyrics"><div className="rhyme-header"><div><h3>Color Rhyme Map</h3><p>{session.lyrics.guidance}</p></div><div className="rhyme-stats"><span>{rhymeAnalysis.scheme||"No scheme"}</span><small>{rhymeAnalysis.lineCount} lines · {rhymeAnalysis.wordCount} words</small></div></div><strong>{session.lyrics.hook}</strong><div className="rhyme-workspace"><label>Lyrics editor<textarea value={lyricsDraft} onChange={(event)=>setLyricsDraft(event.target.value)} placeholder="Write original lyrics here..."/><button type="button" onClick={saveLyrics}>Save lyric revision</button></label><div className="rhyme-preview">{rhymeAnalysis.lines.map((line)=><div className="rhyme-line" key={line.index}><span className="rhyme-scheme" style={{color:line.color||"#64748b"}}>{line.familyId}</span><p>{line.tokens.length?line.tokens.map((token,index)=><span key={`${line.index}-${index}`} className={token.familyId?`rhyme-token ${token.isLineEnding?"ending":""}`:""} style={token.familyId?{color:token.color,backgroundColor:`${token.color}18`}:undefined}>{token.text}</span>):<em>Empty line</em>}</p></div>)}</div></div></section>}
        {manifest&&<section className="audio-manifest"><h3>Export manifest</h3><pre>{JSON.stringify(manifest,null,2)}</pre></section>}
      </>}</main>
    </div>
  </div>;
}
