import React, { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useOSMode } from "../../context/ModeContext.js";
import { OS_MODES } from "../../core/os/modes.js";
import { createPortfolioBlueprint } from "../../core/finance/portfolioPlannerEngine.js";
import LiveSignalPanel from "./LiveSignalPanel.js";
import "./FinanceTradePilot.css";
import "../../styles/finance-realm.css";

const API = process.env.REACT_APP_API_URL || "http://localhost:5000";
const money = (value) => value == null ? "—" : new Intl.NumberFormat("en-US", { style:"currency",currency:"USD",maximumFractionDigits:2 }).format(value);
const defaultSymbols = "SPY,QQQ,DIA,AAPL,MSFT,NVDA,AMZN,GOOGL";

export default function ProMarketsRealm(){
  const {setMode}=useOSMode(); const [symbols,setSymbols]=useState(defaultSymbols); const [feed,setFeed]=useState({quotes:[],crypto:[],freshness:"loading"}); const [ipos,setIpos]=useState({entries:[]}); const [loading,setLoading]=useState(false);
  const [profile,setProfile]=useState({capital:10000,horizonYears:10,emergencyMonths:4,risk:"balanced",includeCrypto:true});
  const blueprint=useMemo(()=>createPortfolioBlueprint(profile),[profile]);
  useEffect(()=>setMode(OS_MODES.FINANCE),[setMode]);
  const refresh=async()=>{setLoading(true);try{const headers={Authorization:`Bearer ${localStorage.getItem("astramind_token")||""}`};const [marketRes,ipoRes]=await Promise.all([fetch(`${API}/api/tradepilot/market-snapshot?symbols=${encodeURIComponent(symbols)}`,{headers}),fetch(`${API}/api/tradepilot/ipo-calendar`,{headers})]);const market=await marketRes.json();const ipo=await ipoRes.json();if(!marketRes.ok)throw new Error(market.error||market.message);if(!ipoRes.ok)throw new Error(ipo.error||ipo.message);setFeed(market);setIpos(ipo);}catch(error){setFeed({quotes:[],crypto:[],freshness:"offline",warning:error.message});}finally{setLoading(false);}};
  useEffect(()=>{refresh();},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const tape=[...(feed.quotes||[]),...(feed.crypto||[])];
  return <main className="finance-module markets-realm"><div className="finance-shell">
    <header className="finance-hero"><div className="finance-eyebrow">Aigenikz Pro Markets · Portfolio contract</div><h1>Pro Markets Observatory</h1><p>Design a diversified portfolio blueprint, inspect licensed market data, research indices, stocks, and crypto, and monitor the upcoming IPO calendar.</p><div className="finance-safety">Educational research—not personalized investment, tax, or legal advice. Prices may be real-time, delayed, end-of-day, or unavailable depending on your provider license. Aigenikz does not execute trades or promise performance.</div></header>
    <RealmNav />
    <section className="market-tape" aria-label="Market ticker"><div className="market-tape-track">{tape.length?tape.concat(tape).map((q,i)=><span key={`${q.symbol}-${i}`}><strong>{q.symbol}</strong> {money(q.price)} <em className={(q.changePercent||0)>=0?"positive":"negative"}>{q.changePercent==null?"":`${q.changePercent>=0?"+":""}${Number(q.changePercent).toFixed(2)}%`}</em></span>):<span>Market feed awaiting licensed provider response</span>}</div></section>
    <div className="market-source"><span>Provider: {feed.provider||"Alpha Vantage + CoinGecko"}</span><span>Freshness: {feed.freshness||"unknown"}</span><button className="finance-button" onClick={refresh}>{loading?"Refreshing…":"Refresh feeds"}</button></div>{feed.warning&&<div className="finance-safety">{feed.warning}</div>}
    <section className="finance-grid">
      <article className="finance-card"><div className="finance-eyebrow">Portfolio DNA</div><h2>Investor profile</h2><div className="finance-form"><Field label="Starting capital" value={profile.capital} set={(v)=>setProfile({...profile,capital:v})}/><Field label="Horizon (years)" value={profile.horizonYears} set={(v)=>setProfile({...profile,horizonYears:v})}/><Field label="Emergency reserve (months)" value={profile.emergencyMonths} set={(v)=>setProfile({...profile,emergencyMonths:v})}/><label>Risk posture<select value={profile.risk} onChange={(e)=>setProfile({...profile,risk:e.target.value})}><option value="conservative">Conservative</option><option value="balanced">Balanced</option><option value="growth">Growth</option></select></label><label className="check-field finance-span-2"><input type="checkbox" checked={profile.includeCrypto} onChange={(e)=>setProfile({...profile,includeCrypto:e.target.checked})}/> Include a capped crypto research sleeve</label></div></article>
      <article className="finance-card wide"><div className="finance-eyebrow">Suggested architecture</div><h2>{blueprint.posture}</h2><div className="portfolio-sleeves">{blueprint.sleeves.map((sleeve)=><div key={sleeve.key}><div className="sleeve-top"><strong>{sleeve.label}</strong><span>{sleeve.percent}% · {money(sleeve.amount)}</span></div><div className="sleeve-bar"><i style={{width:`${sleeve.percent}%`}}/></div><small>{sleeve.examples}</small></div>)}</div><div className="finance-result"><strong>{blueprint.rebalance}</strong><ul>{blueprint.rules.map(rule=><li key={rule}>{rule}</li>)}</ul></div></article>
      <article className="finance-card full"><div className="finance-eyebrow">Market universe</div><h2>Custom ticker watch</h2><p>Enter up to 20 stock or ETF symbols. A real-time “all stocks” feed requires licensed exchange data; this watch surface retrieves the symbols you choose.</p><div className="market-symbol-row"><input className="finance-prompt" value={symbols} onChange={(e)=>setSymbols(e.target.value.toUpperCase())}/><button className="finance-button primary" onClick={refresh}>Load watchlist</button></div><div className="quote-grid">{(feed.quotes||[]).map(q=><div key={q.symbol}><strong>{q.symbol}</strong><span>{money(q.price)}</span><small>{q.timestamp||feed.freshness}</small></div>)}</div></article>
      <article className="finance-card full"><div className="finance-eyebrow">Future listings · next three months</div><h2>IPO Watchtower</h2>{ipos.warning&&<p>{ipos.warning}</p>}<div className="ipo-table"><table className="finance-ledger"><thead><tr><th>Date</th><th>Company</th><th>Symbol</th><th>Exchange</th><th>Expected range</th></tr></thead><tbody>{(ipos.entries||[]).map((ipo,index)=><tr key={`${ipo.symbol}-${index}`}><td>{ipo.ipoDate||"TBA"}</td><td>{ipo.name||"—"}</td><td>{ipo.symbol||"—"}</td><td>{ipo.exchange||"—"}</td><td>{ipo.priceRangeLow||ipo.priceRangeHigh?`${ipo.currency||"$"} ${ipo.priceRangeLow||"?"}–${ipo.priceRangeHigh||"?"}`:"TBA"}</td></tr>)}{!ipos.entries?.length&&<tr><td colSpan="5">No IPO entries returned by the configured provider.</td></tr>}</tbody></table></div><p className="finance-empty-note">IPO dates and ranges are preliminary and can change or be withdrawn. Inclusion is not a recommendation.</p></article>
      <article className="finance-card full pro-signal-shell"><LiveSignalPanel subscriptionTier="finance_pro" accountSize={profile.capital} riskTolerance={profile.risk==="growth"?"high":profile.risk==="conservative"?"low":"medium"}/></article>
    </section>
  </div></main>;
}
function Field({label,value,set}){return <label>{label}<input type="number" min="0" value={value} onChange={(e)=>set(e.target.value)}/></label>}
function RealmNav(){return <div className="finance-tabs"><Link className="finance-tab" to="/finance">← Finance Hub</Link><Link className="finance-tab" to="/finance/income">Trip Planner</Link><Link className="finance-tab active" to="/finance/expenses">Pro Markets</Link><Link className="finance-tab" to="/finance/savings">Wealth Navigator</Link></div>}
