import React, { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useOSMode } from "../../context/ModeContext.js";
import { OS_MODES } from "../../core/os/modes.js";
import { CRUISE_LINES, LODGING_TYPES, RENTAL_PROVIDERS, generateTripOptions } from "../../core/finance/tripPlannerEngine.js";
import "../../styles/finance-realm.css";

const money = (value) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value || 0);
const defaults = { origin: "", destination: "", departDate: "", returnDate: "", travelers: 2, days: 5, modes: ["car", "air", "train", "bus"], carType: "pov", distanceMiles: 500, povMpg: 25, gasPrice: 3.5, parkingTolls: 60, rentalProvider: "Enterprise", rentalDaily: 58, rentalFees: 120, rentalMpg: 28, airFare: 350, airHours: 5, trainFare: 190, trainHours: 9, busFare: 95, busHours: 12, localTransit: 80, lodgingType: "Hotel", lodgingNight: 175, foodDay: 65, activitiesDay: 40, contingencyPercent: 12, cruiseLine: "Carnival", cruiseFare: 650, cruiseFees: 180, cruiseHours: 24, cruiseIncludesLodging: true, cruiseIncludesMeals: true };

export default function TripPlannerRealm() {
  const { setMode } = useOSMode(); const [form, setForm] = useState(defaults); const [generated, setGenerated] = useState(false);
  const options = useMemo(() => generateTripOptions(form), [form]);
  useEffect(() => setMode(OS_MODES.FINANCE), [setMode]);
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const toggleMode = (mode) => set("modes", form.modes.includes(mode) ? form.modes.filter((item) => item !== mode) : [...form.modes, mode]);

  return <main className="finance-module journey-realm"><div className="finance-shell">
    <header className="finance-hero"><div className="finance-eyebrow">AstraMind Journey Intelligence · Trip contract</div><h1>Trip Planner Realm</h1><p>Compare driving, flights, rail, bus, and cruises in one mission—including lodging, meals, activities, rental fees, fuel, tolls, and contingency.</p><div className="finance-safety">Cost estimates are planning scenarios, not live quotes or reservations. Verify schedules, availability, accessibility, insurance, passport/visa rules, and final provider terms before purchasing.</div></header>
    <RealmNav />
    <section className="finance-grid">
      <article className="finance-card full"><div className="finance-eyebrow">Mission coordinates</div><div className="finance-form"><Field label="Origin" value={form.origin} onChange={(v)=>set("origin",v)} /><Field label="Destination" value={form.destination} onChange={(v)=>set("destination",v)} /><Field type="date" label="Depart" value={form.departDate} onChange={(v)=>set("departDate",v)} /><Field type="date" label="Return" value={form.returnDate} onChange={(v)=>set("returnDate",v)} /><Field type="number" label="Travelers" value={form.travelers} onChange={(v)=>set("travelers",v)} /><Field type="number" label="Trip days" value={form.days} onChange={(v)=>set("days",v)} /></div></article>
      <article className="finance-card full"><div className="finance-eyebrow">Transportation matrix</div><h2>Which routes should AstraMind compare?</h2><div className="mode-selector">{[["car","🚗 Car"],["air","✈️ Air"],["train","🚆 Train"],["bus","🚌 Bus"],["cruise","🛳️ Cruise"]].map(([id,label])=><button key={id} className={`finance-tab ${form.modes.includes(id)?"active":""}`} onClick={()=>toggleMode(id)}>{label}</button>)}</div>
        <div className="finance-form planner-subform">
          {form.modes.includes("car") && <><label>Vehicle source<select value={form.carType} onChange={(e)=>set("carType",e.target.value)}><option value="pov">P.O.V. / personal vehicle</option><option value="rental">Rental vehicle</option></select></label>{form.carType === "rental" && <label>Rental company<select value={form.rentalProvider} onChange={(e)=>set("rentalProvider",e.target.value)}>{RENTAL_PROVIDERS.map(x=><option key={x}>{x}</option>)}</select></label>}<Field type="number" label="Round-trip miles" value={form.distanceMiles} onChange={(v)=>set("distanceMiles",v)} /><Field type="number" label={form.carType === "rental"?"Rental daily rate":"Vehicle MPG"} value={form.carType === "rental"?form.rentalDaily:form.povMpg} onChange={(v)=>set(form.carType === "rental"?"rentalDaily":"povMpg",v)} /><Field type="number" label="Gas / gallon" value={form.gasPrice} onChange={(v)=>set("gasPrice",v)} /><Field type="number" label={form.carType === "rental"?"Rental taxes & fees":"Parking & tolls"} value={form.carType === "rental"?form.rentalFees:form.parkingTolls} onChange={(v)=>set(form.carType === "rental"?"rentalFees":"parkingTolls",v)} /></>}
          {form.modes.includes("air") && <><Field type="number" label="Air fare / person" value={form.airFare} onChange={(v)=>set("airFare",v)} /><Field type="number" label="Door-to-door air hours" value={form.airHours} onChange={(v)=>set("airHours",v)} /></>}
          {form.modes.includes("train") && <><Field type="number" label="Train fare / person" value={form.trainFare} onChange={(v)=>set("trainFare",v)} /><Field type="number" label="Train travel hours" value={form.trainHours} onChange={(v)=>set("trainHours",v)} /></>}
          {form.modes.includes("bus") && <><Field type="number" label="Bus fare / person" value={form.busFare} onChange={(v)=>set("busFare",v)} /><Field type="number" label="Bus travel hours" value={form.busHours} onChange={(v)=>set("busHours",v)} /></>}
          {form.modes.includes("cruise") && <><label>Cruise line<select value={form.cruiseLine} onChange={(e)=>set("cruiseLine",e.target.value)}>{CRUISE_LINES.map(x=><option key={x}>{x}</option>)}</select></label><Field type="number" label="Cruise fare / person" value={form.cruiseFare} onChange={(v)=>set("cruiseFare",v)} /><Field type="number" label="Port fees / person" value={form.cruiseFees} onChange={(v)=>set("cruiseFees",v)} /><label className="check-field"><input type="checkbox" checked={form.cruiseIncludesMeals} onChange={(e)=>set("cruiseIncludesMeals",e.target.checked)}/> Meals included</label></>}
          <Field type="number" label="Local transit total" value={form.localTransit} onChange={(v)=>set("localTransit",v)} />
        </div>
      </article>
      <article className="finance-card full"><div className="finance-eyebrow">Stay & experience</div><div className="finance-form"><label>Lodging type<select value={form.lodgingType} onChange={(e)=>set("lodgingType",e.target.value)}>{LODGING_TYPES.map(x=><option key={x}>{x}</option>)}</select></label><Field type="number" label="Lodging / night" value={form.lodgingNight} onChange={(v)=>set("lodgingNight",v)} /><Field type="number" label="Meals / person / day" value={form.foodDay} onChange={(v)=>set("foodDay",v)} /><Field type="number" label="Activities / person / day" value={form.activitiesDay} onChange={(v)=>set("activitiesDay",v)} /><Field type="number" label="Contingency %" value={form.contingencyPercent} onChange={(v)=>set("contingencyPercent",v)} /></div><button className="finance-button primary" onClick={()=>setGenerated(true)} disabled={!form.modes.length}>Generate three best options</button></article>
      {generated && <article className="finance-card full"><div className="finance-eyebrow">AstraMind route ranking</div><h2>Three best planning scenarios</h2><p>Ranked by estimated total cost, door-to-door time, and comfort—not sponsored placement.</p><div className="trip-options">{options.map((option)=><div className={`trip-option rank-${option.rank}`} key={option.mode}><span className="trip-rank">#{option.rank} · {option.badge}</span><h3>{option.icon} {option.label}</h3><div className="trip-price">{money(option.total)}</div><p>{option.details}</p><dl><div><dt>Per traveler</dt><dd>{money(option.perTraveler)}</dd></div><div><dt>Travel time</dt><dd>{option.travelHours} hrs</dd></div><div><dt>Lodging</dt><dd>{money(option.lodging)}</dd></div><div><dt>Food</dt><dd>{money(option.food)}</dd></div><div><dt>Contingency</dt><dd>{money(option.contingency)}</dd></div><div><dt>Fit score</dt><dd>{option.score}/100</dd></div></dl></div>)}</div></article>}
    </section>
  </div></main>;
}

function Field({label,value,onChange,type="text"}) { return <label>{label}<input type={type} min={type==="number"?"0":undefined} value={value} onChange={(e)=>onChange(e.target.value)}/></label>; }
function RealmNav(){return <div className="finance-tabs"><Link className="finance-tab" to="/finance">← Finance Hub</Link><Link className="finance-tab active" to="/finance/income">Trip Planner</Link><Link className="finance-tab" to="/finance/expenses">Pro Markets</Link><Link className="finance-tab" to="/finance/savings">Wealth Navigator</Link></div>;}

