import express from "express";
import db from "../db/sqlite.js";
import AudioSessionStore from "../../core/audio/AudioSessionStore.js";
import { buildAudioExportManifest, composeAudioProject, inferCompositionBrief, updateSessionLyrics, updateTrackMixer } from "../../core/audio/AudioCompositionEngine.js";
import { generateLocalLyrics } from "../../core/audio/LocalLyricEngine.js";
import { renderAstraMindWaveform } from "../../core/audio/AstraMindWaveformProvider.js";
import { getMusicGenerationStatus, renderFullSong } from "../../core/audio/MusicGenerationProvider.js";
import requireAuth from "../middleware/requireAuth.js";

export function createAudioStudioRouter({ store = new AudioSessionStore({ db }), lyricsGenerator = generateLocalLyrics, waveformRenderer = renderAstraMindWaveform, vocalRenderer = renderFullSong, authMiddleware = requireAuth } = {}) {
  const router = express.Router();
  router.use(authMiddleware);
  const userId = (req) => req.user.id;
  router.post("/sessions",async(req,res)=>{try{const id=userId(req);let brief=inferCompositionBrief(req.body);let lyricGeneration=null;const wantsAstraLyrics=brief.lyricsMode!=="manual"&&brief.lyricsMode!=="instrumental"&&!brief.instrumental&&!String(brief.lyricsText||"").trim();if(wantsAstraLyrics){lyricGeneration=await lyricsGenerator({prompt:brief.prompt,title:brief.title,genre:brief.genre,mood:brief.mood,structure:brief.structure,perspective:brief.perspective,rhymeDensity:brief.rhymeDensity,contentRating:brief.contentRating});brief={...brief,title:brief.title||lyricGeneration.suggestedTitle,lyricsText:lyricGeneration.lyrics};}const composed=composeAudioProject(brief);if(composed.lyrics&&lyricGeneration)composed.lyrics={...composed.lyrics,theme:lyricGeneration.theme,keywords:lyricGeneration.keywords,hook:lyricGeneration.hook||composed.lyrics.hook};const session=store.save({...composed,generation:{mode:"single-prompt",lyricsSource:lyricGeneration?.provider||brief.lyricsMode||"manual",warning:lyricGeneration?.warning||null}},id);return res.status(201).json({ok:true,session,warning:lyricGeneration?.warning||null,creditUsage:req.creditReservation||null});}catch(error){return res.status(400).json({ok:false,error:error.message});}});
  router.get("/sessions",(req,res)=>res.json({ok:true,sessions:store.list(userId(req),req.query.limit)}));
  router.get("/sessions/:sessionId",(req,res)=>{const session=store.get(req.params.sessionId,userId(req));return session?res.json({ok:true,session}):res.status(404).json({ok:false,error:"Audio session not found."});});
  router.patch("/sessions/:sessionId/mixer",(req,res)=>{try{const id=userId(req);const current=store.get(req.params.sessionId,id);if(!current)return res.status(404).json({ok:false,error:"Audio session not found."});const session=store.save(updateTrackMixer(current,req.body),id);return res.json({ok:true,session});}catch(error){return res.status(400).json({ok:false,error:error.message});}});
  router.patch("/sessions/:sessionId/lyrics",(req,res)=>{try{const id=userId(req);const current=store.get(req.params.sessionId,id);if(!current)return res.status(404).json({ok:false,error:"Audio session not found."});const session=store.save(updateSessionLyrics(current,req.body?.text),id);return res.json({ok:true,session});}catch(error){return res.status(400).json({ok:false,error:error.message});}});
  router.post("/lyrics/generate",async(req,res)=>{try{const result=await lyricsGenerator(req.body);return res.json({ok:true,...result,creditUsage:req.creditReservation||null});}catch(error){return res.status(400).json({ok:false,error:error.message});}});
  router.post("/sessions/:sessionId/export",(req,res)=>{try{const session=store.get(req.params.sessionId,userId(req));if(!session)return res.status(404).json({ok:false,error:"Audio session not found."});return res.json({ok:true,manifest:buildAudioExportManifest(session,req.body?.format||"wav")});}catch(error){return res.status(400).json({ok:false,error:error.message});}});
  router.post("/sessions/:sessionId/render",(req,res)=>{try{const id=userId(req);const current=store.get(req.params.sessionId,id);if(!current)return res.status(404).json({ok:false,error:"Audio session not found."});const render=waveformRenderer(current);const session=store.save({...current,provider:{status:"native-preview-rendered",audioGenerationConfigured:true,name:"astramind-native"},waveform:render,updatedAt:new Date().toISOString(),version:current.version+1},id);return res.json({ok:true,render,session,creditUsage:req.creditReservation||null});}catch(error){return res.status(400).json({ok:false,error:error.message});}});
  router.post("/sessions/:sessionId/render-vocals",async(req,res)=>{try{const id=userId(req);const current=store.get(req.params.sessionId,id);if(!current)return res.status(404).json({ok:false,error:"Audio session not found."});if(!current.lyrics?.text?.trim())return res.status(400).json({ok:false,error:"Save lyrics before generating a vocal song."});const render=await vocalRenderer(current,{vocalStyle:req.body?.vocalStyle});const session=store.save({...current,provider:{status:"full-song-rendered",audioGenerationConfigured:true,name:render.provider,singingVoiceConfigured:true},vocalRender:render,updatedAt:new Date().toISOString(),version:current.version+1},id);return res.json({ok:true,render,session,creditUsage:req.creditReservation||null});}catch(error){return res.status(502).json({ok:false,error:error.message});}});
  router.delete("/sessions/:sessionId",(req,res)=>store.delete(req.params.sessionId,userId(req))?res.json({ok:true,deleted:true}):res.status(404).json({ok:false,error:"Audio session not found."}));
  router.get("/health",(_req,res)=>{const music=getMusicGenerationStatus();res.json({ok:true,composer:"astramind-composer-v2",studio:"multitrack-session-v1",singlePromptOrchestration:true,waveformProvider:"astramind-native",audioProviderConfigured:true,musicGenerationConfigured:music.configured,musicProvider:music.activeProvider,musicProviderLabel:music.activeProviderLabel,musicModel:music.model,selfHostedMusic:music.selfHosted,musicProviders:music.providers,singingVoiceProvider:music.activeProvider,singingVoiceProviderConfigured:music.configured});});
  return router;
}

export default createAudioStudioRouter();
